/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Artur
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Teste
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblS = new javax.swing.JLabel();
        lblRn = new javax.swing.JLabel();
        lblG = new javax.swing.JLabel();
        lblJ = new javax.swing.JLabel();
        lblU2 = new javax.swing.JLabel();
        lblEs = new javax.swing.JLabel();
        lblEa = new javax.swing.JLabel();
        lblTpm = new javax.swing.JLabel();
        txtS = new javax.swing.JTextField();
        txtRn = new javax.swing.JTextField();
        txtG = new javax.swing.JTextField();
        txtJ = new javax.swing.JTextField();
        txtU2 = new javax.swing.JTextField();
        txtEs = new javax.swing.JTextField();
        txtEa = new javax.swing.JTextField();
        txtTpm = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        txtResultado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblS.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblS.setForeground(new java.awt.Color(0, 0, 255));
        lblS.setText("S = ");
        lblS.setToolTipText("Bla\n");

        lblRn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblRn.setForeground(new java.awt.Color(0, 0, 255));
        lblRn.setText("Rn =");

        lblG.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblG.setForeground(new java.awt.Color(0, 0, 255));
        lblG.setText("G = ");

        lblJ.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblJ.setForeground(new java.awt.Color(0, 0, 255));
        lblJ.setText("J =");

        lblU2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblU2.setForeground(new java.awt.Color(0, 0, 255));
        lblU2.setText("U2 =");

        lblEs.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblEs.setForeground(new java.awt.Color(0, 0, 255));
        lblEs.setText("Es =");

        lblEa.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblEa.setForeground(new java.awt.Color(0, 0, 255));
        lblEa.setText("Ea =");

        lblTpm.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblTpm.setForeground(new java.awt.Color(0, 0, 255));
        lblTpm.setText("Tpm =");

        txtS.setForeground(new java.awt.Color(0, 0, 255));
        txtS.setToolTipText("Declividade da curva de pressão de vapor em relação à Temperatura (kPa°C)");
        txtS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSActionPerformed(evt);
            }
        });

        txtRn.setForeground(new java.awt.Color(0, 0, 255));
        txtRn.setToolTipText("Saldo em radiação (MJ/m² dia)");
        txtRn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRnActionPerformed(evt);
            }
        });

        txtG.setForeground(new java.awt.Color(0, 0, 255));
        txtG.setToolTipText("Fluxo de Calor");
        txtG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGActionPerformed(evt);
            }
        });

        txtJ.setForeground(new java.awt.Color(0, 0, 255));
        txtJ.setToolTipText("Constante psicrométrica");
        txtJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJActionPerformed(evt);
            }
        });

        txtU2.setForeground(new java.awt.Color(0, 0, 255));
        txtU2.setToolTipText("Velocidade do vento a 2 m de altura (m s -1 )");

        txtEs.setForeground(new java.awt.Color(0, 0, 255));
        txtEs.setToolTipText("Pressão de saturação de vapor (kPa)");

        txtEa.setForeground(new java.awt.Color(0, 0, 255));
        txtEa.setToolTipText("Pressão atual de vapor (kPa)");

        txtTpm.setForeground(new java.awt.Color(0, 0, 255));
        txtTpm.setToolTipText("Temperatura média do ar (ºC)");
        txtTpm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTpmActionPerformed(evt);
            }
        });

        btnCalcular.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(0, 0, 255));
        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        lblResultado.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblResultado.setForeground(new java.awt.Color(0, 0, 255));
        lblResultado.setText("Resultado =");

        txtResultado.setForeground(new java.awt.Color(0, 0, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("          Teste de Evapotranspiração");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblJ)
                    .addComponent(lblG)
                    .addComponent(lblRn)
                    .addComponent(lblS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtS)
                    .addComponent(txtRn)
                    .addComponent(txtG)
                    .addComponent(txtJ, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblU2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtU2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTpm)
                            .addComponent(lblEs)
                            .addComponent(lblEa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEs)
                            .addComponent(txtTpm)
                            .addComponent(txtEa, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblResultado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
            .addGroup(layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(btnCalcular)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblS)
                    .addComponent(lblU2)
                    .addComponent(txtS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtU2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRn)
                    .addComponent(lblEs)
                    .addComponent(txtRn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblG)
                    .addComponent(lblEa)
                    .addComponent(txtG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJ)
                    .addComponent(lblTpm)
                    .addComponent(txtJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTpm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCalcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResultado)
                    .addComponent(txtResultado))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSActionPerformed

    private void txtRnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRnActionPerformed

    private void txtTpmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTpmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTpmActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
    
    Double S = Double.parseDouble(txtS.getText());
    Double Rn = Double.parseDouble(txtRn.getText());
    Double G = Double.parseDouble(txtG.getText());
    Double J = Double.parseDouble(txtJ.getText());
    Double U2 = Double.parseDouble(txtU2.getText());
    Double Es = Double.parseDouble(txtEs.getText());
    Double Ea = Double.parseDouble(txtEa.getText());
    Double Tpm = Double.parseDouble(txtTpm.getText());
    
    Double Resultado = (0.408 * S) * (Rn - G) + (((J * 900) * U2) * (Es - Ea)/Tpm + 273) / S + J * (1 + (0.34 * U2)); 
    
    txtResultado.setText(String.valueOf(Resultado));  
    
    

    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGActionPerformed

    private void txtJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEa;
    private javax.swing.JLabel lblEs;
    private javax.swing.JLabel lblG;
    private javax.swing.JLabel lblJ;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblRn;
    private javax.swing.JLabel lblS;
    private javax.swing.JLabel lblTpm;
    private javax.swing.JLabel lblU2;
    private javax.swing.JTextField txtEa;
    private javax.swing.JTextField txtEs;
    private javax.swing.JTextField txtG;
    private javax.swing.JTextField txtJ;
    private javax.swing.JTextField txtResultado;
    private javax.swing.JTextField txtRn;
    private javax.swing.JTextField txtS;
    private javax.swing.JTextField txtTpm;
    private javax.swing.JTextField txtU2;
    // End of variables declaration//GEN-END:variables
}
